### ISSUE TITLE
Use variables in JSON

### ISSUE THREAD

**Issue by scott-doyland-burrows** [Azure/appservice-settings#29]
Hi,

I have the same issue as:

https://github.com/Azure/appservice-settings/issues/6

I want to pass in a variable to the JSON, like this:

```
jobs:
  app-settings:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "MYSECRET=MYSEC" >> $GITHUB_ENV
      - uses: azure/appservice-settings@v1
        with:
          mask-inputs: false
          app-name: 'my-app'
          app-settings-json: |
            [
              {
                "name": "DOCKER_REGISTRY_SERVER_PASSWORD1",
                "value": $(MYSECRET),
                "slotSetting": false
              }
            ]
```

using $(MYSECRET) causes the GitHub Actions to fail, it says invalid JSON.

I believe this type of variable substitution works for Azure DevOps - but it is not working in GitHub Actions.

How do I insert my envvar $MYSECRET into the JSON.

Alternatively, is there a way to read in a JSON file (not a GitHub secret) rather than putting the JSON inline.
If so I could replace the secrets as needed.  I do NOT want to use a GitHub secret as I want to pull my secrets from Azure KeyVault.

(I know the above code would expose the secret - I would handle the masking earlier when I actually set this up).

Thanks.

**Comment by kanika1894** [comment]
Yes, you are right, this variable substitution works for DevOps but support doesn't exist in Actions.
As of now, support to read in a JSON file (not a GitHub secret) rather than putting the JSON inline, does not exist.

One of the way to insert envvar $MYSECRET into the JSON can be using [variable substitution action](https://github.com/microsoft/variable-substitution).
You can follow these steps:
1. Use this action to substitute values in json https://github.com/microsoft/variable-substitution
2. read this json file in some env variable
3. use this env variable as input.

For app-settings action, valid json is required as input.

Hope this helps 😊
